def transform_input(input_string):
    elements = input_string.split('\n')
    transformed_string = ','.join(elements)
    return transformed_string

input_data = """stem-cells-for-knee-cartilage-regeneration-korea
lams-korea
premature-ejaculation-korea
urolift-korea
blood-purification-korea
facelift-in-korea
premarital-check-up-korea
female-incontinence-korea
cheekbone-reduction-surgery-in-korea
thread-lift-in-korea
how-to-fix-inverted-nipples-korea
benign-prostatic-hypertrophy-korea
under-eye-fat-removal-korea
liposuction-in-korea
linear-frim-laser-lifting-korea
philtrum-reduction-korea
clippy-c-braces-korea
hip-dip-fat-grafting-korea
facial-feminization-surgery-korea
sclerotherapy-korea
abortion-korea
areola-surgery-korea
braces-korea
facial-treatment-korea
microblading-korea
gum-bleaching-korea
cost-face-lift-korea
cost-eye-surgery-korea
presbyopia-correction-korea
tip-plasty-korea
vaginal-tightening-laser-korea
clitoroplasty-korea
revision-clitoroplasty-korea
vaginoplasty-korea
labiaplasty-korea
phalloplasty-korea
cost-of-hair-transplant-in-korea
hair-loss-vs-hair-transplant-korea
cost-liposuction-korea
full-face-filler-in-korea
under-eye-fillers-korea
facial-laser-hair-removal-korea
hyaluronidase-korea
collagen-booster-korea
nose-thread-lift-korea
hairline-laser-hair-removal-korea
nose-fillers-korea
laser-toning-korea
kybella-korea
restylane-korea
rejuran-healer-korea
radiesse-korea
botox-in-korea
revision-breast-surgery-korea
veneers-in-korea
hyperhidrosis-laser-korea
stem-cell-hair-treatment-korea
petit-vaginal-plastic-surgery-korea
stem-cell-disease-therapy-korea
erectile-dysfunction-korea
prp-facial-treatment-korea
teeth-cleaning-korea
penis-filler-korea
all-ceramic-veneers-korea
teeth-crown-korea
scalp-care-korea
clitoroplasty-with-laser-korea
periodontal-disease-treatment-korea
penis-enlargement-korea
vaginal-bleaching-korea
vaginal-dryness-korea
adenomyosis-korea
autologous-stem-cell-therapy-korea
bruxism-treatment-korea
circumcision-korea
vaginal-implant-korea
clitoral-hood-reduction-korea
vaginal-filler-korea
vasectomy-korea
stem-cell-facial-korea
wisdom-tooth-removal-korea
neuroplasty-korea
viveve-laser-korea
stem-cell-acne-scar-korea
inlay-filling-korea
glans-enlargement-korea
ovarian-cancer-screening-korea
lip-microblading-korea
silicone-penile-implant-korea
penis-lengthening-korea
resin-filling-korea
brazilian-butt-lift-korea
stem-cell-scalp-therapy-korea
mini-liposuction-korea
pubic-fat-pad-removal-korea
penile-implant-korea
labia-majora-whitening-korea
teeth-whitening-korea
cost-of-nose-job-in-korea
sauna-after-rhinoplasty
genioplasty-korea
how-fix-hawk-nose-korea
hair-loss-treatment-in-korea
fixing-crooked-teeth-korea
double-chin-tightening-korea
breast-reduction-korea
breast-augmentation-korea
labia-minora-whitening-korea
under-eye-fat-grafting-korea
how-fix-bulbous-nose-korea
clear-choice-dental-implants-korea
chin-surgery-korea
calf-reduction-surgery-korea
spider-veins-treatment-korea
breast-implant-in-korea
breast-surgery-korea
double-jaw-surgery-korea
full-body-liposuction-korea
nose-implant-korea
face-contouring-korea
lymphatic-massages-after-liposuction-korea
sweat-gland-removal-korea
jaw-surgery-in-korea
varicose-veins-treatment-korea
breast-fat-grafting-korea
nk-cell-test-korea
ptosis-correction-korea
chin-liposuction-korea
sagging-after-facial-liposuction-korea
thigh-liposuction-korea
alar-reduction-korea
transgender-friendly-clinics-korea
uterine-fibroids-treatment-korea"""

output_data = transform_input(input_data)
print(output_data)
